controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|de
    defaults:
        _locale: en

api:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute

public:
    resource:
        path: ../src/Controller/Web/
        namespace: App\Controller\Web
    type: attribute

root:
    path: /
    controller: App\Controller\Home\HomeController
